### ISSUE TITLE
Metamask sign

### ISSUE THREAD

**Issue by mateeej00** [infotrex/bulk-upload-to-opensea#11]
At the end, I have to manually confirm (Sign) Metamask for each NFT loaded.
Loads everything automatically, but does not confirm Metamask automatically.

Erorr message:

![Software_Issue](https://user-images.githubusercontent.com/96474310/147759740-bca213c6-76f4-4515-9d8b-c6e6f87b7bae.jpg)

**Comment by mateeej00** [comment]
This part needs to be deleted from the program, but I don't have access to the code. 

![Software_Delete](https://user-images.githubusercontent.com/96474310/147759839-61182d1b-1f74-4fa3-8742-36919cc3ae78.jpg)

**Comment by HiimNaruto** [comment]
I got the same issue. Still looking for a solution.

**Comment by HiimNaruto** [comment]
> This part needs to be deleted from the program, but I don't have access to the code.
> 
> ![Software_Delete](https://user-images.githubusercontent.com/96474310/147759839-61182d1b-1f74-4fa3-8742-36919cc3ae78.jpg)

How did you open this file btw ?

**Comment by mateeej00** [comment]
I didn't. This must be arranged by the person who created the program.

**Comment by HiimNaruto** [comment]
how did you get that screenshot then :O 
btw he will fix this issue soon I guess. He was online a few hours ago

**Comment by mateeej00** [comment]
Yes, he changed code and for me WORKS.

This is new "software file": upload-sign.py

**Comment by HiimNaruto** [comment]
Hey. Thank you very much. I will check that too <2

**Comment by senosuke** [comment]
![image](https://user-images.githubusercontent.com/96891749/147791342-2f2d51cb-167f-4bdd-9b1f-78ed894bae29.png)
My proble same with you, is not automatically sign metamask, this the code that show in my terminal

**Comment by infotrex** [comment]
try to use the another file called upload-sign.py.
please update me if the file are work.

TQ

**Comment by ManojPrasha9394** [comment]
Same issue here

**Comment by infotrex** [comment]
don't know why, some user are okey,
but some cannot.
still need to found out.

**Comment by ManojPrasha9394** [comment]
We used windows 10
is that issue?

(when try on ubunutu can't open chrome browser)

**Comment by infotrex** [comment]
windows don't have any major issue

**Comment by mateeej00** [comment]
Check this: https://www.youtube.com/watch?v=dj5oOPaeIqI

**Comment by senosuke** [comment]
> try to use the another file called upload-sign.py. please update me if the file are work.
> 
> TQ

Still not working sir

**Comment by infotrex** [comment]
try upload-sign2.py.
thx

**Comment by senosuke** [comment]
![image](https://user-images.githubusercontent.com/96891749/147855949-19640526-01d9-459f-8b12-d964a30064e1.png)
![image](https://user-images.githubusercontent.com/96891749/147855957-f1cf16ff-957a-40be-bfab-ace9d6b37109.png)


> try upload-sign2.py. thx

Still the same sir, is there problem because im using Ethereum Blockchain?

**Comment by ph1lg00d** [comment]
Hi all, 
try to help with information you need to fix the problem with the sign question on the end. 
I've the same error.
My NFT Collection is setup with polygon network (about the eth gas) 

Let me know if I can help you for troubelshooting - and thanks for that awesome project :)

Cheers and a Happy New Year!

Phil

**Comment by infotrex** [comment]
> ![image](https://user-images.githubusercontent.com/96891749/147855949-19640526-01d9-459f-8b12-d964a30064e1.png) ![image](https://user-images.githubusercontent.com/96891749/147855957-f1cf16ff-957a-40be-bfab-ace9d6b37109.png)
> 
> > try upload-sign2.py. thx
> 
> Still the same sir, is there problem because im using Ethereum Blockchain?

Please full screen your chrome browser during process.

**Comment by infotrex** [comment]
> Hi all, try to help with information you need to fix the problem with the sign question on the end. I've the same error. My NFT Collection is setup with polygon network (about the eth gas)
> 
> Let me know if I can help you for troubelshooting - and thanks for that awesome project :)
> 
> Cheers and a Happy New Year!
> 
> Phil

try to use upload-sign.py or upload-sign2.py.
thx

**Comment by senosuke** [comment]
> > > try upload-sign2.py. thx
> > 
> > 
> > Still the same sir, is there problem because im using Ethereum Blockchain?
> 
> Please full screen your chrome browser during process.

Still no change sir, i

**Comment by infotrex** [comment]
> > 
> > Please full screen your chrome browser during process.
> 
> Still no change sir, i

if the 2 files didn't solve the issue, then might be other issue for that.

**Comment by ph1lg00d** [comment]
Jap - Sign2 worked for me! Thank you so much :)

**Comment by senosuke** [comment]
> > > Please full screen your chrome browser during process.
> > 
> > 
> > Still no change sir, i
> 
> if the 2 files didn't solve the issue, then might be other issue for that.

Okay, i think because im using Ethereum Blockchain?

**Comment by infotrex** [comment]
Once of the user are using Ethereum Blockchain are no problem.
because many scenario are out of my control, 
please twitter me @klvntss if you want further checking.

**Comment by ManojPrasha9394** [comment]
Sign2 worked for me! Thank you

**Comment by thekesslereffect** [comment]
Sign2 still gives me the same error but it happens right away instead of 50+ items later.
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "<string>", line 320, in main_program_loop
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 514, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()="Sign"]"}
  (Session info: chrome=96.0.4664.110)
Stacktrace:
Backtrace:
        Ordinal0 [0x00576903+2517251]
        Ordinal0 [0x0050F8E1+2095329]
        Ordinal0 [0x00412848+1058888]
        Ordinal0 [0x0043D448+1233992]
        Ordinal0 [0x0043D63B+1234491]
        Ordinal0 [0x00467812+1406994]
        Ordinal0 [0x0045650A+1336586]
        Ordinal0 [0x00465BBF+1399743]
        Ordinal0 [0x0045639B+1336219]
        Ordinal0 [0x004327A7+1189799]
        Ordinal0 [0x00433609+1193481]
        GetHandleVerifier [0x00705904+1577972]
        GetHandleVerifier [0x007B0B97+2279047]
        GetHandleVerifier [0x00606D09+534521]
        GetHandleVerifier [0x00605DB9+530601]
        Ordinal0 [0x00514FF9+2117625]
        Ordinal0 [0x005198A8+2136232]
        Ordinal0 [0x005199E2+2136546]
        Ordinal0 [0x00523541+2176321]
        BaseThreadInitThunk [0x776CFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77C37A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77C37A6E+238]`

**Comment by infotrex** [comment]
Sign error you can try file
upload-sign.py or upload-sign2.py.

TQ

**Comment by thekesslereffect** [comment]
Yep I tried both upload-sign.py and upload-sign2.py and got the same issue. Seems like it just can’t find the window for some reason. Or maybe it could try searching multiple times until found then continuing

**Comment by infotrex** [comment]
> Yep I tried both upload-sign.py and upload-sign2.py and got the same issue. Seems like it just can’t find the window for some reason. Or maybe it could try searching multiple times until found then continuing

Pls try the latest file "upload-sign.py" to resolved the sign issue.

**Comment by SIM-888** [comment]
that new file does not resolve the sign issue

**Comment by yepyep3** [comment]
Hi - Also have the sign issue.  Stalls at the sign stage & just downloaded the new files.

Sorry for noob question, but how do I try upload-sign2 vs 1?  

Thx for the work on this!

**Comment by infotrex** [comment]
> that new file does not resolve the sign issue

are you using eth or polygon?

**Comment by yepyep3** [comment]
> > that new file does not resolve the sign issue
> 
> are you using eth or polygon?

Polygon  (but polygon box unticked)

**Comment by infotrex** [comment]
set your chrome browser to maximize size before start running,
twitte me if still want more feature checking.

**Comment by yepyep3** [comment]
Still not working at maximized browser - appreciate the help but not working as of yet.  Any other ideas?  Twt you as well - thx

**Comment by Momchil1** [comment]
Hello, I believe the problem with the metamask sign in is with the slower networks (like mine). The program is trying to reference an element (the sign in button) before it is created. So one solution might be if the creator can set a bigger time period in seconds in order to allow the metamask window to show up and after that the program to try to click it.
Another solution (the better in my opinion) is to check constantly if the button is created and only after that the program to proceed with its working.
Currently if the program can't find the button the whole work flow is stopping with an error in the console. And this is happening very often.
Apart of this issue, this program is very useful. Thanks for shering.

**Comment by infotrex** [comment]
> but still the problem occurs after each 15-20 uploads. Apart of this issue, this program is very useful. Thanks for shearing.

@Momchil1 
i just upload the latest version upload.py, please try for it.
TQ

**Comment by SIM-888** [comment]
@infotrex my apologies. that new upload.py file did work. For some reason its not friendly with the eth network. I re created my collection on polygon and it works beautiful. 

Theres a 3 step confirmation process when listing and on eth, i think thats where the malfuction comes in.

**Comment by Momchil1** [comment]
Thanks for the fast fix @infotrex. I can see you've added a delay right before the sign in button click, which works a lot better. In 100+ uploads the sign in panel froze only once. I'm on the ETH network.
There are rare occasions when the following message pops up, but it's obviously from the Opensea side:
Oops, something went wrong
Yikes, looks like something went wrong on our end. If the issue persists, please shoot us a note so we can help out.
I guess you can't do anything about it.
Maybe if the program could start the process again after a crash from the point where it was before the crash, that might be a solution, but I guess it will complicate things a lot.
Anyway thanks for the efforts.

**Comment by infotrex** [comment]
> Still not working at maximized browser - appreciate the help but not working as of yet. Any other ideas? Twt you as well - thx

@yepyep3  pls you the latest "upload.py" file.

**Comment by yepyep3** [comment]
> > Still not working at maximized browser - appreciate the help but not working as of yet. Any other ideas? Twt you as well - thx
> 
> @yepyep3 pls you the latest "upload.py" file.

I checked & unchecked the complete listing box - with it unchecked, it works but doesn't go through the sell/listing steps - with "complete listing" unchecked it stalls out at the screen that says sell for some reason.

Thanks for all your work on this!

**Comment by kevindeepitm** [comment]
> ![image](https://user-images.githubusercontent.com/96891749/147855949-19640526-01d9-459f-8b12-d964a30064e1.png) ![image](https://user-images.githubusercontent.com/96891749/147855957-f1cf16ff-957a-40be-bfab-ace9d6b37109.png)
> 
> > try upload-sign2.py. thx
> 
> Still the same sir, is there problem because im using Ethereum Blockchain?

I have the same problem, on a probability basis, using the latest version (Jan 12) of upload-sign.py
The program can usually upload 10-20 NFTs without issues, but every now and then it will get stuck at the sign page and I had to manually sign. My longest streak was 50 successful uploads without human intervention, and half of them happen at the Metamask sign page.
I think my internet is decently fast though.

**Comment by infotrex** [comment]
@kevindeepitm
pls download the latest file will resolved this issue.
Remember check "polygon blockchain" if you are using polygon.
TQ

kelvin

**Comment by infotrex** [comment]
> ![image](https://user-images.githubusercontent.com/95880481/149255558-de236244-6551-42d1-a4a9-3fab69cf0ea4.png)
> 
> Hi, I downloaded the script a few minutes ago and have this problem, how can i fix it?
> 
> Thanks!

@Berseck20
should signed your metamask account before run the application.

**Comment by Berseck20** [comment]
My bad, sorry.

im new in this world

**Comment by HiimNaruto** [comment]
> 

I got the same problem with the new version. did you find any solution?
