### ISSUE TITLE
no continue after listing and need restart

### ISSUE THREAD

**Issue by Dantuzzu** [infotrex/bulk-upload-to-opensea#125]
when the program listing not continue the loop, in cmd i see this error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Utente\Desktop\Crypto earth\bulk-upload-to-opensea-main\upload18.py", line 444, in main_program_loop
    driver.find_element(By.XPATH, '//button[text()="Sign"]').click()
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()="Sign"]"}
  (Session info: chrome=99.0.4844.82)

**Comment by Dantuzzu** [comment]
i resolved, need only waith xd

**Comment by jdmakwana555** [comment]
please explain?
