### ISSUE TITLE
unable to connect to renderer

### ISSUE THREAD

**Issue by VladHefner** [infotrex/bulk-upload-to-opensea#128]
please help ....wtf ? unable to connect to renderer
chromedriver is ok. Please Helps

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wasco\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\wasco\Downloads\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main\upload.py", line 229, in main_program_loop
    driver = webdriver.Chrome( service=Service(project_path + "/chromedriver.exe"), options=opt, )
  File "C:\Users\wasco\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\wasco\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\wasco\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\wasco\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\wasco\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\wasco\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
  (Session info: chrome=99.0.4844.51)
Stacktrace:
Backtrace:
        Ordinal0 [0x00E77AC3+2587331]
        Ordinal0 [0x00E0ADD1+2141649]
        Ordinal0 [0x00D03BB8+1063864]
        Ordinal0 [0x00CF4077+999543]
        Ordinal0 [0x00D04EF0+1068784]
        Ordinal0 [0x00D4E16C+1368428]
        Ordinal0 [0x00D4CD5A+1363290]
        Ordinal0 [0x00D484A6+1344678]
        Ordinal0 [0x00D253F6+1201142]
        Ordinal0 [0x00D262E6+1204966]
        GetHandleVerifier [0x0101DF22+1680738]
        GetHandleVerifier [0x010D0DBC+2413564]
        GetHandleVerifier [0x00F0D151+563089]
        GetHandleVerifier [0x00F0BF13+558419]
        Ordinal0 [0x00E1081E+2164766]
        Ordinal0 [0x00E15508+2184456]
        Ordinal0 [0x00E15650+2184784]
        Ordinal0 [0x00E1F5BC+2225596]
        BaseThreadInitThunk [0x774338F4+36]
        RtlUnicodeStringToInteger [0x779D56C3+595]
        RtlUnicodeStringToInteger [0x779D568E+542]

**Comment by infotrex** [comment]
@VladHefner
you may open too many chrome browser at the same time,
try close all and open again. thx
