### ISSUE TITLE
Error captcha

### ISSUE THREAD

**Issue by Capi666** [infotrex/bulk-upload-to-opensea#134]
Hi,

I have the Buster extension and I filled the API key, but the program does not clicked in the option "I´m not a robot"
I am using the last version of upload_captcha.py

I have that error:
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\xxxx\Desktop\bulk-upload-to-opensea-main2\bulk-upload-to-opensea-main\upload_captcha.py", line 403, in main_program_loop
    capt_btn = driver.find_element_by_xpath("//button[@id='solver-button']")
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 514, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@id='solver-button']"}
  (Session info: chrome=99.0.4844.82)

Any idea?

Thanks and regards,

**Comment by infotrex** [comment]
@Capi666
this error message look like the script cannot found the buster solver button.
may i know your buster optional configure setting?

**Comment by Capi666** [comment]
> @Capi666 this error message look like the script cannot found the buster solver button. may i know your buster optional configure setting?

Solved: The problem was I have the option "Simulate user interaction" and It should be unchecked.
