### ISSUE TITLE
Stopped adding Properties,, any suggestions 

### ISSUE THREAD

**Issue by ramidalloul** [infotrex/bulk-upload-to-opensea#224]
Hi Guys, thanks for your consist support.. it was all ok till this happen and stopped adding Properties

Start creating NFT My Zombie #3847
number  3847
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\new downloads\nft\to upload\bulk-upload-to-opensea-main\upload_2captcha V2.py", line 399, in main_program_loop
    input1 = driver.find_element(By.XPATH, '//tbody[@class="AssetTraitsForm--body"]/tr[last()]/td[1]/div/div/input')
  File "C:\Users\RAMI\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\RAMI\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\RAMI\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unexpected command response
  (Session info: chrome=103.0.5060.53)
Stacktrace:
Backtrace:
        Ordinal0 [0x0112D953+2414931]
        Ordinal0 [0x010BF5E1+1963489]
        Ordinal0 [0x00FAC6B8+837304]
        Ordinal0 [0x00F9EB34+781108]
        Ordinal0 [0x00F9E06A+778346]
        Ordinal0 [0x00F9D646+775750]
        Ordinal0 [0x00F9CEBC+773820]
        Ordinal0 [0x00F9CD59+773465]
        Ordinal0 [0x00FADA70+842352]
        Ordinal0 [0x010040DB+1196251]
        Ordinal0 [0x00FF42B6+1131190]
        Ordinal0 [0x00FCE860+976992]
        Ordinal0 [0x00FCF756+980822]
        GetHandleVerifier [0x0139CC62+2510274]
        GetHandleVerifier [0x0138F760+2455744]
        GetHandleVerifier [0x011BEABA+551962]
        GetHandleVerifier [0x011BD916+547446]
        Ordinal0 [0x010C5F3B+1990459]
        Ordinal0 [0x010CA898+2009240]
        Ordinal0 [0x010CA985+2009477]
        Ordinal0 [0x010D3AD1+2046673]
        BaseThreadInitThunk [0x7594FA29+25]
        RtlGetAppContainerNamedObjectPath [0x76FE7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x76FE7A6E+238]

**Comment by MisakiNFT** [comment]
i had this problem. there might be some typos on the particular metadata

**Comment by maximedrn** [comment]
This error means that the element is not accessible or its XPATH does not match. Unfortunately, this happens when you try to set an XPATH that is too precise.

I advice to look at this repository: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale
It works like this bot. Everything is explained in more detail and I can help you if you need help.

**Comment by karakule3dfx** [comment]
@maximedrn is wrong. the problem is stop caused by chrome update. You can use downgrade or use the upper beta version.(chrome driver)

**Comment by ramidalloul** [comment]
> This error means that the element is not accessible or its XPATH does not match. Unfortunately, this happens when you try to set an XPATH that is too precise.
> 
> I advice to look at this repository: https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale It works like this bot. Everything is explained in more detail and I can help you if you need help.

thanks a lot for your help.. I will try this bot in the next collection

**Comment by ramidalloul** [comment]
> @maximedrn is wrong. the problem is stop caused by chrome update. You can use downgrade or use the upper beta version.(chrome driver)

appreciated a lot .. now it's working ..prefect

**Comment by karakule3dfx** [comment]
@ramidalloul I'm glad the problem was fixed
