### ISSUE TITLE
failed recaptcha

### ISSUE THREAD

**Issue by hamhocks** [infotrex/bulk-upload-to-opensea#229]
Not going past the create page here is the error. Any solutions?

C:\Users\slots\OneDrive\Desktop\bulk-upload-to-opensea-main\upload_2captcha_V2.py:249: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=project_path + "/chromedriver.exe",options=options)

**Comment by karakule3dfx** [comment]
Can you take a screenshot of the program interface? Also, write what you want to do so I can help. If you explain the problem you are having in more detail, I can help you faster.

**Comment by Edijaime** [comment]
> Você pode tirar uma captura de tela da interface do programa? Além disso, escreva o que você quer fazer para que eu possa ajudar. Se você explicar o problema que está tendo com mais detalhes, posso ajudá-lo mais rapidamente.


I'm having the same error. This message appears in cmd and crashes everything.

**Comment by karakule3dfx** [comment]
@Edijaime  
Can you take a screenshot of the program interface? Also, write what you want to do so I can help. If you explain the problem you are having in more detail, I can help you faster.

**Comment by Edijaime** [comment]
> @Edijaime Can you take a screenshot of the program interface? Also, write what you want to do so I can help. If you explain the problem you are having in more detail, I can help you faster.

I don't have this problem anymore. What's happening now is it doesn't list nft to sell. Eventually hangs on this screen. I've already changed the chromedriver version but it doesn't help.



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\junior\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\junior\Downloads\bulk-upload-to-opensea-main\bulk-upload-to-opensea-main\upload_2captcha_V2.py", line 527, in main_program_loop
    capt_btn = driver.find_element_by_xpath("//button[@id='solver-button']")
  File "C:\Users\junior\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 514, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\junior\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\junior\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\junior\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@id='solver-button']"}
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
        Ordinal0 [0x00CED953+2414931]
        Ordinal0 [0x00C7F5E1+1963489]
        Ordinal0 [0x00B6C6B8+837304]
        Ordinal0 [0x00B99500+1021184]
        Ordinal0 [0x00B9979B+1021851]
        Ordinal0 [0x00BC6502+1205506]
        Ordinal0 [0x00BB44E4+1131748]
        Ordinal0 [0x00BC4812+1198098]
        Ordinal0 [0x00BB42B6+1131190]
        Ordinal0 [0x00B8E860+976992]
        Ordinal0 [0x00B8F756+980822]
        GetHandleVerifier [0x00F5CC62+2510274]
        GetHandleVerifier [0x00F4F760+2455744]
        GetHandleVerifier [0x00D7EABA+551962]
        GetHandleVerifier [0x00D7D916+547446]
        Ordinal0 [0x00C85F3B+1990459]
        Ordinal0 [0x00C8A898+2009240]
        Ordinal0 [0x00C8A985+2009477]
        Ordinal0 [0x00C93AD1+2046673]
        BaseThreadInitThunk [0x76BE3744+36]
        RtlSetCurrentTransaction [0x771DA064+212]
        RtlSetCurrentTransaction [0x771DA02F+159]

**Comment by hamhocks** [comment]
It’s working fine now mysteriously. I couldn’t get it to work yesterday at all.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
