### ISSUE TITLE
Chrome Version

### ISSUE THREAD

**Issue by dtrade84** [infotrex/bulk-upload-to-opensea#244]
The installation file for the driver update is not working. Any ideas?

**Comment by fbc33** [comment]
google chrome and chromedriver version must be the same.
First find out what version of your google chrome browser and  https://chromedriver.chromium.org/  download the same chromedriver version from this site.
Then you have to delete the old chromedriver in the bulk-upload-to-opensea folder and replace it with the new chromedriver.
good luck

**Comment by dtrade84** [comment]
Same thing. Still not working.

**Comment by dtrade84** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Pictures\NFT\bulk-upload-to-opensea-main\upload_2captcha_V2.py", line 249, in main_program_loop
    driver = webdriver.Chrome(executable_path=project_path + "/chromedriver.exe",options=options)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Daniel\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at localhost:8989
from session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 106.0.5249.119
Stacktrace:
Backtrace:
        Ordinal0 [0x00902733+2434867]
        Ordinal0 [0x008907A1+1968033]
        Ordinal0 [0x0077C678+837240]
        Ordinal0 [0x0079CAC3+969411]
        Ordinal0 [0x007960DB+942299]
        Ordinal0 [0x00795EA6+941734]
        Ordinal0 [0x007C90B0+1151152]
        Ordinal0 [0x007C8D0A+1150218]
        Ordinal0 [0x007C4256+1131094]
        Ordinal0 [0x0079E840+976960]
        Ordinal0 [0x0079F736+980790]
        GetHandleVerifier [0x00B73C72+2515426]
        GetHandleVerifier [0x00B6702F+2463135]
        GetHandleVerifier [0x009A522A+620442]
        GetHandleVerifier [0x009A4016+615814]
        Ordinal0 [0x0089707B+1994875]
        Ordinal0 [0x0089B938+2013496]
        Ordinal0 [0x0089BA25+2013733]
        Ordinal0 [0x008A4DE1+2051553]
        BaseThreadInitThunk [0x7769FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77857BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77857B8E+238]
