### ISSUE TITLE
chrome not  opening on clicking start

### ISSUE THREAD

**Issue by kartik9844** [infotrex/bulk-upload-to-opensea#271]
DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=project_path + "/chromedriver.exe",options=options)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\kartik joshi\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\kartik joshi\Desktop\programming\opeansea\bulk\bulk-upload-to-opensea-main\upload_2captcha_V2.py", line 249, in main_program_loop
    driver = webdriver.Chrome(executable_path=project_path + "/chromedriver.exe",options=options)
  File "C:\Users\kartik joshi\Desktop\programming\opeansea\bulk\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\kartik joshi\Desktop\programming\opeansea\bulk\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\kartik joshi\Desktop\programming\opeansea\bulk\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\kartik joshi\Desktop\programming\opeansea\bulk\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\kartik joshi\Desktop\programming\opeansea\bulk\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\kartik joshi\Desktop\programming\opeansea\bulk\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at localhost:8989
from chrome not reachable
Stacktrace:
Backtrace:
        GetHandleVerifier [0x01018893+48451]
        (No symbol) [0x00FAB8A1]
        (No symbol) [0x00EB4F20]
        (No symbol) [0x00EAB0E5]
        (No symbol) [0x00ED5858]
        (No symbol) [0x00ED0151]
        (No symbol) [0x00ECFF31]
        (No symbol) [0x00F00798]
        (No symbol) [0x00F0047C]
        (No symbol) [0x00EFA0B6]
        (No symbol) [0x00ED7E08]
        (No symbol) [0x00ED8F2D]
        GetHandleVerifier [0x01278E3A+2540266]
        GetHandleVerifier [0x012B8959+2801161]
        GetHandleVerifier [0x012B295C+2776588]
        GetHandleVerifier [0x010A2280+612144]
        (No symbol) [0x00FB4F6C]
        (No symbol) [0x00FB11D8]
        (No symbol) [0x00FB12BB]
        (No symbol) [0x00FA4857]
        BaseThreadInitThunk [0x766A7D49+25]
        RtlInitializeExceptionChain [0x7770B74B+107]
        RtlClearBits [0x7770B6CF+191]

**Comment by Gaviar** [comment]
Hello, the version of the browser and the driver is not the same.. the data is a beast
