### ISSUE TITLE
blob error and freeze at properties

### ISSUE THREAD

**Issue by hunekune** [infotrex/bulk-upload-to-opensea#51]
Hi there,
I got two errors. One is blob as I can't see my image.
![blob](https://user-images.githubusercontent.com/99019675/152526909-a80442bc-9130-479b-9145-51b928965976.png)
And the other is it gets freezed at properties. The error says,
```
number  0
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hoon\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 314, in main_program_loop
  File "<string>", line 227, in wait_xpath
  File "C:\Users\Hoon\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until   
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00F56903+2517251]
        Ordinal0 [0x00EEF8E1+2095329]
        Ordinal0 [0x00DF2848+1058888]
        Ordinal0 [0x00E1D448+1233992]
        Ordinal0 [0x00E1D63B+1234491]
        Ordinal0 [0x00E47812+1406994]
        Ordinal0 [0x00E3650A+1336586]
        Ordinal0 [0x00E45BBF+1399743]
        Ordinal0 [0x00E3639B+1336219]
        Ordinal0 [0x00E127A7+1189799]
        Ordinal0 [0x00E13609+1193481]
        GetHandleVerifier [0x010E5904+1577972]
        GetHandleVerifier [0x01190B97+2279047]
        GetHandleVerifier [0x00FE6D09+534521]
        GetHandleVerifier [0x00FE5DB9+530601]
        Ordinal0 [0x00EF4FF9+2117625]
        Ordinal0 [0x00EF98A8+2136232]
        Ordinal0 [0x00EF99E2+2136546]
        Ordinal0 [0x00F03541+2176321]
        BaseThreadInitThunk [0x75A5F989+25]
        RtlGetAppContainerNamedObjectPath [0x77A674B4+228]
        RtlGetAppContainerNamedObjectPath [0x77A67484+180]

```
What am I missing? My Chrome driver is 96 and I exactly followed you instruction video.
Thank you for your hard work and your answer would be really really appreciated.

**Comment by infotrex** [comment]
do you select "src" this folder?
and image format should be like 1.png ....

**Comment by hunekune** [comment]
I definately select "src" folder.
and image format is like 1.png ...10000.png. The json files as well.

**Comment by hunekune** [comment]
And I got this messege sometimes too. Would it be helpful to solve the problem?
```
number  0
<string>:263: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:268: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:272: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:276: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:327: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hoon\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 335, in main_program_loop
  File "<string>", line 248, in wait_xpath
  File "C:\Users\Hoon\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until   
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00F56903+2517251]
        Ordinal0 [0x00EEF8E1+2095329]
        Ordinal0 [0x00DF2848+1058888]
        Ordinal0 [0x00E1D448+1233992]
        Ordinal0 [0x00E1D63B+1234491]
        Ordinal0 [0x00E47812+1406994]
        Ordinal0 [0x00E3650A+1336586]
        Ordinal0 [0x00E45BBF+1399743]
        Ordinal0 [0x00E3639B+1336219]
        Ordinal0 [0x00E127A7+1189799]
        Ordinal0 [0x00E13609+1193481]
        GetHandleVerifier [0x010E5904+1577972]
        GetHandleVerifier [0x01190B97+2279047]
        GetHandleVerifier [0x00FE6D09+534521]
        GetHandleVerifier [0x00FE5DB9+530601]
        Ordinal0 [0x00EF4FF9+2117625]
        Ordinal0 [0x00EF98A8+2136232]
        Ordinal0 [0x00EF99E2+2136546]
        Ordinal0 [0x00F03541+2176321]
        BaseThreadInitThunk [0x75A5F989+25]
        RtlGetAppContainerNamedObjectPath [0x77A674B4+228]
        RtlGetAppContainerNamedObjectPath [0x77A67484+180]
```

**Comment by CCPixel8** [comment]
Same for me too

**Comment by infotrex** [comment]
@hunekune @CCPixel8


> And I got this messege sometimes too. Would it be helpful to solve the problem?
> 
> ```
**> number  0**
> <string>:263: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead

do you see the number 0?
do your start number you put 0?

**Comment by infotrex** [comment]
> Same for me too

select correct "src" folder with valid filename?

**Comment by hunekune** [comment]
> @hunekune @CCPixel8
> 
> > And I got this messege sometimes too. Would it be helpful to solve the problem?
> 
> **> number 0**
> 
> > :263: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
> 
> do you see the number 0? do your start number you put 0?

Yes I did. It's 0 to 9999

**Comment by infotrex** [comment]
your number should start from 1 instead of 0.
thx

**Comment by hunekune** [comment]
i put 0 and 9999.
i'm having the smae problem. blob error and freezing at properties.
```
number  1
<string>:263: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:268: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:272: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:276: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
<string>:327: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hoon\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 335, in main_program_loop
  File "<string>", line 248, in wait_xpath
  File "C:\Users\Hoon\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until     
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x011B6903+2517251]
        Ordinal0 [0x0114F8E1+2095329]
        Ordinal0 [0x01052848+1058888]
        Ordinal0 [0x0107D448+1233992]
        Ordinal0 [0x0107D63B+1234491]
        Ordinal0 [0x010A7812+1406994]
        Ordinal0 [0x0109650A+1336586]
        Ordinal0 [0x010A5BBF+1399743]
        Ordinal0 [0x0109639B+1336219]
        Ordinal0 [0x010727A7+1189799]
        Ordinal0 [0x01073609+1193481]
        GetHandleVerifier [0x01345904+1577972]
        GetHandleVerifier [0x013F0B97+2279047]
        GetHandleVerifier [0x01246D09+534521]
        GetHandleVerifier [0x01245DB9+530601]
        Ordinal0 [0x01154FF9+2117625]
        Ordinal0 [0x011598A8+2136232]
        Ordinal0 [0x011599E2+2136546]
        Ordinal0 [0x01163541+2176321]
        BaseThreadInitThunk [0x7533F989+25]
        RtlGetAppContainerNamedObjectPath [0x771474B4+228]
        RtlGetAppContainerNamedObjectPath [0x77147484+180]
```

**Comment by infotrex** [comment]
pls check your json structure same like this
https://github.com/infotrex/bulk-upload-to-opensea/blob/main/src/json/1.json

must include 
"attributes": [
    {
      "trait_type": "BACKGROUND",
      "value": "Gold Yellow"
    }.....
