### ISSUE TITLE
i have a problem ? 

### ISSUE THREAD

**Issue by OpteYT** [infotrex/bulk-upload-to-opensea#63]
if you use the code python uplode.py 

upload.py:211: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
upload.py:211: DeprecationWarning: use options instead of chrome_options
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<string>", line 211, in main_program_loop
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 72, in __init__ 
    service_log_path, service, keep_alive)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 99, in __init__
    options=options)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__    self.start_session(capabilities, browser_profile)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute 
    self.error_handler.check_response(response)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at localhost:8989
from session not created: This version of ChromeDriver only supports Chrome version 96
Current browser version is 98.0.4758.82
Stacktrace:
Backtrace:
        Ordinal0 [0x00FA6903+2517251]
        Ordinal0 [0x00F3F8E1+2095329]
        Ordinal0 [0x00E42848+1058888]
        Ordinal0 [0x00E60B9D+1182621]
        Ordinal0 [0x00E5A3FB+1156091]
        Ordinal0 [0x00E5A1E1+1155553]
        Ordinal0 [0x00E8AAAF+1354415]
        Ordinal0 [0x00E8A71A+1353498]
        Ordinal0 [0x00E8639B+1336219]
        Ordinal0 [0x00E627A7+1189799]
        Ordinal0 [0x00E63609+1193481]
        GetHandleVerifier [0x01135904+1577972]
        GetHandleVerifier [0x011E0B97+2279047]
        GetHandleVerifier [0x01036D09+534521]
        GetHandleVerifier [0x01035DB9+530601]
        Ordinal0 [0x00F44FF9+2117625]
        Ordinal0 [0x00F498A8+2136232]
        Ordinal0 [0x00F499E2+2136546]
        Ordinal0 [0x00F53541+2176321]
        BaseThreadInitThunk [0x75E3FA29+25]
        RtlGetAppContainerNamedObjectPath [0x76ED7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x76ED7A6E+238]

**Comment by ZacharyAkers** [comment]
@OpteYT to get rid of depreciation warnings make sure you are using upload18.py instead of upload.py. As for chromedriver check what version of chrome you are using on [https://www.whatismybrowser.com](url) then go to [https://chromedriver.chromium.org/downloads](url) download the version of chrome you are using from there, replace your chromedriver.exe in your folder/directory with one you just downloaded. should be fixed then
