### ISSUE TITLE
chrome error

### ISSUE THREAD

**Issue by Xamius** [infotrex/bulk-upload-to-opensea#71]
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "F:\opensea-creatures-master\upload18.py", line 225, in main_program_loop
    driver = webdriver.Chrome( service=Service(project_path + "/chromedriver.exe"), options=opt, )
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'`
upload18.py
I checked the versions, loaded different ones.
I read all the posts and tried to fix it, it did not work. What is the problem?

**Comment by ZacharyAkers** [comment]
@Xamius double check you have service imported on line 25, if you do then delete script and reinstall it.

**Comment by infotrex** [comment]
@Xamius
What OS you run for this script?

**Comment by Xamius** [comment]
> @infotrex 
Windows 10
And everything works great

> @ZacharyAkers
Thank you
