### ISSUE TITLE
Open Chrome Browser

### ISSUE THREAD

**Issue by 061221kaa** [infotrex/bulk-upload-to-opensea#9]
when we press the Open Chrome Browser button, we get a message on the terminal like this. can you help?

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "<string>", line 65, in open_chrome_profile
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

**Comment by infotrex** [comment]
seem like some error the permission folder or maybe chrome profile.
thx

**Comment by simtechnos** [comment]
its more like the chromium driver is not there for the Mac and there is no Mac command for it.

**Comment by infotrex** [comment]
not compatible to Mac Os at the moment.
Will do it, if have more user demand request.

TQ
